"""
Database schema for Smart City Safety System.

Tables:
  - incidents     : raw events (accident, fire, flood, crime…)
  - predictions   : ML model output linked to an incident
  - alerts        : triggered alerts (Telegram / email etc.)
  - hotspots      : pre-computed high-risk geo zones
"""

import enum
from datetime import datetime

from geoalchemy2 import Geometry
from sqlalchemy import (
    BigInteger, Boolean, Column, DateTime, Enum,
    Float, ForeignKey, Integer, String, Text,
)
from sqlalchemy.orm import relationship

from app.database import Base


# ── Enumerations 

class IncidentType(str, enum.Enum):
    ACCIDENT   = "ACCIDENT"
    FIRE       = "FIRE"
    FLOOD      = "FLOOD"
    CRIME      = "CRIME"
    CROWD      = "CROWD"       # dangerous crowd surge
    MEDICAL    = "MEDICAL"
    NORMAL     = "NORMAL"      # no emergency


class IncidentSource(str, enum.Enum):
    CCTV       = "CCTV"        # computer vision on video feed
    SOCIAL     = "SOCIAL"      # NLP on tweet / news text
    SENSOR     = "SENSOR"      # IoT sensor
    MANUAL     = "MANUAL"      # operator entered
    SIMULATED  = "SIMULATED"   # generated by our data simulator


class RiskLevel(str, enum.Enum):
    LOW      = "LOW"
    MEDIUM   = "MEDIUM"
    HIGH     = "HIGH"
    CRITICAL = "CRITICAL"


class AlertStatus(str, enum.Enum):
    PENDING  = "PENDING"
    SENT     = "SENT"
    FAILED   = "FAILED"


# ── Table 1: Incidents 

class Incident(Base):
    """
    One row = one real-world event detected by any source.
    The location column stores a PostGIS Point geometry.
    """
    __tablename__ = "incidents"

    id            = Column(BigInteger, primary_key=True, autoincrement=True)
    created_at    = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at    = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # What happened and where
    incident_type = Column(Enum(IncidentType), nullable=False, index=True)
    source        = Column(Enum(IncidentSource), nullable=False)
    description   = Column(Text, nullable=True)          # raw text if from NLP source
    raw_data      = Column(Text, nullable=True)          # original JSON payload as string

    # Geography — PostGIS Point(longitude, latitude), SRID 4326 = standard GPS
    location      = Column(Geometry("POINT", srid=4326), nullable=False)
    latitude      = Column(Float, nullable=False)        # stored plain too for easy queries
    longitude     = Column(Float, nullable=False)
    area_name     = Column(String(200), nullable=True)   # e.g. "Hazratganj, Lucknow"

    # Timing
    occurred_at   = Column(DateTime, nullable=True)      # when it actually happened
    is_active     = Column(Boolean, default=True)        # False = resolved

    # Relationships
    predictions   = relationship("Prediction", back_populates="incident", cascade="all, delete-orphan")
    alerts        = relationship("Alert",      back_populates="incident", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Incident id={self.id} type={self.incident_type} area={self.area_name}>"


# ── Table 2: Predictions 

class Prediction(Base):
    """
    ML model output for a given incident.
    One incident can have multiple predictions (one per model run / version).
    """
    __tablename__ = "predictions"

    id             = Column(BigInteger, primary_key=True, autoincrement=True)
    created_at     = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    incident_id    = Column(BigInteger, ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False, index=True)

    # Risk scoring engine output
    risk_score     = Column(Float,  nullable=False)           # 0.0 – 100.0
    risk_level     = Column(Enum(RiskLevel), nullable=False, index=True)

    # Individual signal scores (0.0 – 1.0 each)
    cv_score       = Column(Float,  nullable=True)            # computer vision
    nlp_score      = Column(Float,  nullable=True)            # NLP urgency
    location_score = Column(Float,  nullable=True)            # hotspot multiplier
    time_score     = Column(Float,  nullable=True)            # peak-hour factor

    # Model metadata — critical for MLOps
    model_name     = Column(String(100), nullable=True)       # e.g. "distilbert-emergency-v2"
    model_version  = Column(String(50),  nullable=True)       # e.g. "2.1.0"
    confidence     = Column(Float, nullable=True)             # 0.0 – 1.0

    # Explanation — what drove the score (for interview demos)
    explanation    = Column(Text, nullable=True)

    # Relationship
    incident       = relationship("Incident", back_populates="predictions")

    def __repr__(self):
        return f"<Prediction incident={self.incident_id} score={self.risk_score} level={self.risk_level}>"


# ── Table 3: Alerts 

class Alert(Base):
    """
    Every notification dispatched (Telegram, email, web push).
    Lets us audit what was sent, when, and whether it succeeded.
    """
    __tablename__ = "alerts"

    id            = Column(BigInteger, primary_key=True, autoincrement=True)
    created_at    = Column(DateTime, default=datetime.utcnow, nullable=False)

    incident_id   = Column(BigInteger, ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False, index=True)

    channel       = Column(String(50), nullable=False)        # "telegram" / "email" / "websocket"
    status        = Column(Enum(AlertStatus), default=AlertStatus.PENDING, nullable=False)
    message       = Column(Text, nullable=False)
    sent_at       = Column(DateTime, nullable=True)
    error_message = Column(Text, nullable=True)               # if FAILED, why?

    incident      = relationship("Incident", back_populates="alerts")

    def __repr__(self):
        return f"<Alert incident={self.incident_id} channel={self.channel} status={self.status}>"


# ── Table 4: Hotspots 

class Hotspot(Base):
    """
    Pre-computed high-risk zones used by the Risk Scoring Engine
    as the location_score signal.

    These are updated periodically by the ML pipeline.
    """
    __tablename__ = "hotspots"

    id             = Column(Integer, primary_key=True, autoincrement=True)
    updated_at     = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    area_name      = Column(String(200), nullable=False, unique=True)
    latitude       = Column(Float, nullable=False)
    longitude      = Column(Float, nullable=False)
    radius_meters  = Column(Float, default=500.0)             # zone radius

    # Risk multiplier 0.0–1.0 — used as location_score in risk engine
    risk_weight    = Column(Float, nullable=False, default=0.5)

    # What kind of incidents are common here
    dominant_type  = Column(Enum(IncidentType), nullable=True)
    incident_count = Column(Integer, default=0)               # historical count

    def __repr__(self):
        return f"<Hotspot area={self.area_name} risk={self.risk_weight}>"